tables:
    protector_access:
        options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        columns:
            ip:
                name: ip
                type: string
                default: 0.0.0.0
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            request_uri:
                name: request_uri
                type: string
                default: ''
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            malicious_actions:
                name: malicious_actions
                type: string
                default: ''
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            expire:
                name: expire
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
        indexes:
            ip:
                name: ip
                columns: [ip]
                unique: false
                primary: false
            request_uri:
                name: request_uri
                columns: [request_uri]
                unique: false
                primary: false
            malicious_actions:
                name: malicious_actions
                columns: [malicious_actions]
                unique: false
                primary: false
            expire:
                name: expire
                columns: [expire]
                unique: false
                primary: false
    protector_log:
        options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        columns:
            lid:
                name: lid
                type: integer
                default: null
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: true
                columnDefinition: null
                comment: null
            uid:
                name: uid
                type: integer
                default: '0'
                notnull: true
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: true
                autoincrement: false
                columnDefinition: null
                comment: null
            ip:
                name: ip
                type: string
                default: 0.0.0.0
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            type:
                name: type
                type: string
                default: ''
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            agent:
                name: agent
                type: string
                default: ''
                notnull: true
                length: 255
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            description:
                name: description
                type: text
                default: null
                notnull: false
                length: 65535
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            extra:
                name: extra
                type: text
                default: null
                notnull: false
                length: 65535
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
                collation: utf8mb4_unicode_ci
            timestamp:
                name: timestamp
                type: datetime
                default: null
                notnull: false
                length: null
                precision: 10
                scale: 0
                fixed: false
                unsigned: false
                autoincrement: false
                columnDefinition: null
                comment: null
        indexes:
            PRIMARY:
                name: PRIMARY
                columns: [lid]
                unique: true
                primary: true
            uid:
                name: uid
                columns: [uid]
                unique: false
                primary: false
            ip:
                name: ip
                columns: [ip]
                unique: false
                primary: false
            type:
                name: type
                columns: [type]
                unique: false
                primary: false
            timestamp:
                name: timestamp
                columns: [timestamp]
                unique: false
                primary: false
